spring.application.name=account-b
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/account_b
spring.datasource.username=saga
spring.datasource.password=saga

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092